Add missing icc profile when saving webp
wix-playground/govips pull request #30
Opened 2020-11-04 17:40 UTC by alon-ne

When saving webp, if the source image had an ICC profile, set profile to sRGB of sGRAY, by number of channels. Unlike  OptimizeICCProfile, CMYK is ignored.

2020-11-04 20:58 UTC, Elad-Laufer requested changes
See inline comment. Also, I suspect that this applies to all "savers" not just webp

2020-11-04 20:58 UTC, Elad-Laufer commented on vips/foreign.c
> +	const char* profile = "none";
I think that setting the profile should happen higher up, we lose control when it's down here.

2020-11-08 10:25 UTC, Elad-Laufer reviewed
"none"?

2020-11-08 10:25 UTC, Elad-Laufer commented on vips/foreign.c
> +		"profile", target_profile ? target_profile : "none",
"none"?

2020-11-08 10:41 UTC, alon-ne commented on vips/foreign.c
> +		"profile", target_profile ? target_profile : "none",
yep

2020-11-08 10:42 UTC, alon-ne commented on vips/foreign.c
> +		"profile", target_profile ? target_profile : "none",
https://libvips.github.io/libvips/API/current/libvips-colour.html#vips-profile-load

2020-11-09 11:03 UTC, Elad-Laufer approved these changes

2020-11-09 15:29 UTC, closed without merging