support SVG >=10MB
wix-playground/govips pull request #37
Opened 2021-03-01 12:46 UTC by idanya

Support loading of big SVG files.
Issue: https://github.com/libvips/libvips/issues/1354
Func def: https://github.com/libvips/libvips/blob/15f4d935aad704818cb786413f6f90b29857b304/libvips/foreign/svgload.c#L775

2021-03-01 14:02 UTC, alon-ne reviewed
What do we do with "SvgDriver" and is that affected by the size limitation? Do I understand correctly that SvgDriver only optimizes images and then libvips opens them, or does it handle the whole svg thing?

See here: https://github.com/wix-private/media-platform-image-manipulator/blob/fb5eb2fd6fd7898b3d61f5890c2320a132d0c9ad/processor/driver/gosvg.go

2021-03-01 14:21 UTC, alon-ne commented
I see in libvips code that it sets a flag called `RSVG_HANDLE_FLAG_UNLIMITED`
and it says 
```
Disable safety limits in the XML parser. Libxml2 has several limits designed to keep malicious XML content from consuming too much memory while parsing. For security reasons, this should only be used for trusted input! 
```
sounds risky

https://developer.gnome.org/rsvg/stable/rsvg-Using-RSVG-with-GIO.html

2021-03-01 14:26 UTC, idanya commented
> What do we do with "SvgDriver" in IM and is that affected by the size limitation? Do I understand correctly that SvgDriver only optimizes images and then libvips opens them, or does it handle the whole svg thing?
> 
> See here: https://github.com/wix-private/media-platform-image-manipulator/blob/fb5eb2fd6fd7898b3d61f5890c2320a132d0c9ad/processor/driver/gosvg.go

we use it when the encoder is SVG, not the decoder.
https://github.com/wix-private/media-platform-image-manipulator/blob/7a16786ab9cfdd1e851a8aa9887d69edb38bf4a6/processor/manipulator.go#L41

2021-03-01 14:41 UTC, idanya commented
> I see in libvips code that it sets a flag called `RSVG_HANDLE_FLAG_UNLIMITED`
> and it says
> 
> > Disable safety limits in the XML parser. Libxml2 has several limits designed to keep malicious XML content from consuming too much memory while parsing. For security reasons, this should only be used for trusted input!
> 
> sounds risky
> 
> https://developer.gnome.org/rsvg/stable/rsvg-Using-RSVG-with-GIO.html

I agree. 

But this is the only solution in order to support the SVG that raised this issue (bigger than 10Mb with embedded images). Unless we want to fork the libs as well (I don't).

Remember that any content inside the SVG is embedded, so if we manipulate it, it already passed the upload size restrictions.

2021-03-01 15:05 UTC, alon-ne commented
> > I see in libvips code that it sets a flag called `RSVG_HANDLE_FLAG_UNLIMITED`
> > and it says
> > > Disable safety limits in the XML parser. Libxml2 has several limits designed to keep malicious XML content from consuming too much memory while parsing. For security reasons, this should only be used for trusted input!
> > 
> > 
> > sounds risky
> > https://developer.gnome.org/rsvg/stable/rsvg-Using-RSVG-with-GIO.html
> 
> I agree.
> 
> But this is the only solution in order to support the SVG that raised this issue (bigger than 10Mb with embedded images). Unless we want to fork the libs as well (I don't).
> 
> Remember that any content inside the SVG is embedded, so if we manipulate it, it already passed the upload size restrictions.

Yes but the way SVG works you can do kind of scripting, so if I understand correctly you can do kind of a loop in a small file that will result in a very big file

2021-03-02 15:22 UTC, Elad-Laufer requested changes
Don't hard code it TRUE, we can set it to true from upper up the code (in IM)

2021-03-02 15:44 UTC, idanya commented
> Don't hard code it TRUE, we can set it to true from upper up the code (in IM)

moved to ENV

2021-03-02 16:20 UTC, Elad-Laufer approved these changes
Looks OK to me, lets see what the C guys have to say

2021-03-04 12:07 UTC, golanpa approved these changes

2021-03-04 12:08 UTC, merged